#!/usr/bin/env bash

# you can uncomment rapydml and rapydcss if you have them installed
#rapydml stocks.pyml && mv stocks.html output/
#rapydcss stocks.sass && mv stocks.css output/
nodejs ../../bin/rapydscript stocks.pyj -p -o stocks.js && mv stocks.js output/
